volumes:
  user_files:

networks:
  postgres:
    external: true

  seq:
    external: true

  internal:

services:
  artisan.next:
    container_name: artisan.next
    restart: unless-stopped
    image: artisan.next
    build:
      context: .
      dockerfile: Artisan.Next/Dockerfile
    env_file:
      - .env
    networks:
      - seq
      - postgres
      - internal
    volumes:
      - user_files:/app/wwwroot/files
    expose:
      - "8080"

  nginx:
    container_name: nginx
    restart: unless-stopped
    image: nginx
    ports:
      - 9995:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - artisan.next
    networks:
      - internal