volumes: 
  user_files:

networks:
  postgres:
    external: true

  seq:
    external: true

services:
  artisan.next:
    container_name: artisan.next
    restart: unless-stopped
    image: artisan.next
    build:
      context: .
      dockerfile: Artisan.Next/Dockerfile
    env_file:
      - .env
    networks:
      - seq
      - postgres
    volumes:
      - user_files:/app/wwwroot/files
        
  nginx:
    container_name: nginx
    restart: unless-stopped
    image: nginx
    ports:
      - 9995:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
